// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.3
// source: ichat.message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageSyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageSyncRequest) Reset() {
	*x = MessageSyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSyncRequest) ProtoMessage() {}

func (x *MessageSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSyncRequest.ProtoReflect.Descriptor instead.
func (*MessageSyncRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{0}
}

type MessageSyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageSyncResponse) Reset() {
	*x = MessageSyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSyncResponse) ProtoMessage() {}

func (x *MessageSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSyncResponse.ProtoReflect.Descriptor instead.
func (*MessageSyncResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{1}
}

type MessageRecallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageRecallRequest) Reset() {
	*x = MessageRecallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecallRequest) ProtoMessage() {}

func (x *MessageRecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecallRequest.ProtoReflect.Descriptor instead.
func (*MessageRecallRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{2}
}

type MessageRecallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageRecallResponse) Reset() {
	*x = MessageRecallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecallResponse) ProtoMessage() {}

func (x *MessageRecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecallResponse.ProtoReflect.Descriptor instead.
func (*MessageRecallResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{3}
}

type MessageAckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageAckRequest) Reset() {
	*x = MessageAckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageAckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAckRequest) ProtoMessage() {}

func (x *MessageAckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAckRequest.ProtoReflect.Descriptor instead.
func (*MessageAckRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{4}
}

type MessageAckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageAckResponse) Reset() {
	*x = MessageAckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageAckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAckResponse) ProtoMessage() {}

func (x *MessageAckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAckResponse.ProtoReflect.Descriptor instead.
func (*MessageAckResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{5}
}

type MessageRespRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageRespRequest) Reset() {
	*x = MessageRespRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRespRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRespRequest) ProtoMessage() {}

func (x *MessageRespRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRespRequest.ProtoReflect.Descriptor instead.
func (*MessageRespRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{6}
}

type MessageRespResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MessageRespResponse) Reset() {
	*x = MessageRespResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRespResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRespResponse) ProtoMessage() {}

func (x *MessageRespResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRespResponse.ProtoReflect.Descriptor instead.
func (*MessageRespResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{7}
}

type TalkToUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From     string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To       string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Type     int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Extra    string `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`
	SendTime int64  `protobuf:"varint,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
}

func (x *TalkToUserRequest) Reset() {
	*x = TalkToUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalkToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkToUserRequest) ProtoMessage() {}

func (x *TalkToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkToUserRequest.ProtoReflect.Descriptor instead.
func (*TalkToUserRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{8}
}

func (x *TalkToUserRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TalkToUserRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TalkToUserRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TalkToUserRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TalkToUserRequest) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *TalkToUserRequest) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type TalkToUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId int64 `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *TalkToUserResponse) Reset() {
	*x = TalkToUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalkToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkToUserResponse) ProtoMessage() {}

func (x *TalkToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkToUserResponse.ProtoReflect.Descriptor instead.
func (*TalkToUserResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{9}
}

func (x *TalkToUserResponse) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type TalkToGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TalkToGroupRequest) Reset() {
	*x = TalkToGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalkToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkToGroupRequest) ProtoMessage() {}

func (x *TalkToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkToGroupRequest.ProtoReflect.Descriptor instead.
func (*TalkToGroupRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{10}
}

type TalkToGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TalkToGroupResponse) Reset() {
	*x = TalkToGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalkToGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkToGroupResponse) ProtoMessage() {}

func (x *TalkToGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkToGroupResponse.ProtoReflect.Descriptor instead.
func (*TalkToGroupResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{11}
}

type TalkToRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TalkToRoomRequest) Reset() {
	*x = TalkToRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalkToRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkToRoomRequest) ProtoMessage() {}

func (x *TalkToRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkToRoomRequest.ProtoReflect.Descriptor instead.
func (*TalkToRoomRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{12}
}

type TalkToRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TalkToRoomResponse) Reset() {
	*x = TalkToRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalkToRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkToRoomResponse) ProtoMessage() {}

func (x *TalkToRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkToRoomResponse.ProtoReflect.Descriptor instead.
func (*TalkToRoomResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{13}
}

// 通知
type NoticeToUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoticeToUserRequest) Reset() {
	*x = NoticeToUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeToUserRequest) ProtoMessage() {}

func (x *NoticeToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeToUserRequest.ProtoReflect.Descriptor instead.
func (*NoticeToUserRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{14}
}

type NoticeToUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoticeToUserResponse) Reset() {
	*x = NoticeToUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeToUserResponse) ProtoMessage() {}

func (x *NoticeToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeToUserResponse.ProtoReflect.Descriptor instead.
func (*NoticeToUserResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{15}
}

type NoticeToGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoticeToGroupRequest) Reset() {
	*x = NoticeToGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeToGroupRequest) ProtoMessage() {}

func (x *NoticeToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeToGroupRequest.ProtoReflect.Descriptor instead.
func (*NoticeToGroupRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{16}
}

type NoticeToGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoticeToGroupResponse) Reset() {
	*x = NoticeToGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoticeToGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeToGroupResponse) ProtoMessage() {}

func (x *NoticeToGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeToGroupResponse.ProtoReflect.Descriptor instead.
func (*NoticeToGroupResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{17}
}

// 会话
type SessionListGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SessionListGetRequest) Reset() {
	*x = SessionListGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionListGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionListGetRequest) ProtoMessage() {}

func (x *SessionListGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionListGetRequest.ProtoReflect.Descriptor instead.
func (*SessionListGetRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{18}
}

type SessionListGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SessionListGetResponse) Reset() {
	*x = SessionListGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionListGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionListGetResponse) ProtoMessage() {}

func (x *SessionListGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionListGetResponse.ProtoReflect.Descriptor instead.
func (*SessionListGetResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{19}
}

type SessionRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SessionRemoveRequest) Reset() {
	*x = SessionRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRemoveRequest) ProtoMessage() {}

func (x *SessionRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRemoveRequest.ProtoReflect.Descriptor instead.
func (*SessionRemoveRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{20}
}

type SessionRemoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SessionRemoveResponse) Reset() {
	*x = SessionRemoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRemoveResponse) ProtoMessage() {}

func (x *SessionRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRemoveResponse.ProtoReflect.Descriptor instead.
func (*SessionRemoveResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{21}
}

type SessionSettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SessionSettingRequest) Reset() {
	*x = SessionSettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSettingRequest) ProtoMessage() {}

func (x *SessionSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSettingRequest.ProtoReflect.Descriptor instead.
func (*SessionSettingRequest) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{22}
}

type SessionSettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SessionSettingResponse) Reset() {
	*x = SessionSettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_message_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSettingResponse) ProtoMessage() {}

func (x *SessionSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_message_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSettingResponse.ProtoReflect.Descriptor instead.
func (*SessionSettingResponse) Descriptor() ([]byte, []int) {
	return file_ichat_message_proto_rawDescGZIP(), []int{23}
}

var File_ichat_message_proto protoreflect.FileDescriptor

var file_ichat_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x14, 0x0a, 0x12, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x15, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17,
	0x0a, 0x15, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x97, 0x01, 0x0a, 0x11, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x54, 0x61, 0x6c,
	0x6b, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x54,
	0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x54, 0x61, 0x6c, 0x6b, 0x54,
	0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x0a,
	0x13, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x6f,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x6f,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a,
	0x15, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x16, 0x0a, 0x14, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa7, 0x06, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x3e, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x12,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x79, 0x6e, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x61, 0x6c,
	0x6c, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x41, 0x63, 0x6b, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61,
	0x6c, 0x6b, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3e, 0x0a, 0x0b, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x6c,
	0x6b, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3b, 0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x6c, 0x6b, 0x54, 0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x6c, 0x6b, 0x54,
	0x6f, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x74, 0x69,
	0x63, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x0d, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e,
	0x5a, 0x1c, 0x69, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ichat_message_proto_rawDescOnce sync.Once
	file_ichat_message_proto_rawDescData = file_ichat_message_proto_rawDesc
)

func file_ichat_message_proto_rawDescGZIP() []byte {
	file_ichat_message_proto_rawDescOnce.Do(func() {
		file_ichat_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_ichat_message_proto_rawDescData)
	})
	return file_ichat_message_proto_rawDescData
}

var file_ichat_message_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_ichat_message_proto_goTypes = []interface{}{
	(*MessageSyncRequest)(nil),     // 0: pb.MessageSyncRequest
	(*MessageSyncResponse)(nil),    // 1: pb.MessageSyncResponse
	(*MessageRecallRequest)(nil),   // 2: pb.MessageRecallRequest
	(*MessageRecallResponse)(nil),  // 3: pb.MessageRecallResponse
	(*MessageAckRequest)(nil),      // 4: pb.MessageAckRequest
	(*MessageAckResponse)(nil),     // 5: pb.MessageAckResponse
	(*MessageRespRequest)(nil),     // 6: pb.MessageRespRequest
	(*MessageRespResponse)(nil),    // 7: pb.MessageRespResponse
	(*TalkToUserRequest)(nil),      // 8: pb.TalkToUserRequest
	(*TalkToUserResponse)(nil),     // 9: pb.TalkToUserResponse
	(*TalkToGroupRequest)(nil),     // 10: pb.TalkToGroupRequest
	(*TalkToGroupResponse)(nil),    // 11: pb.TalkToGroupResponse
	(*TalkToRoomRequest)(nil),      // 12: pb.TalkToRoomRequest
	(*TalkToRoomResponse)(nil),     // 13: pb.TalkToRoomResponse
	(*NoticeToUserRequest)(nil),    // 14: pb.NoticeToUserRequest
	(*NoticeToUserResponse)(nil),   // 15: pb.NoticeToUserResponse
	(*NoticeToGroupRequest)(nil),   // 16: pb.NoticeToGroupRequest
	(*NoticeToGroupResponse)(nil),  // 17: pb.NoticeToGroupResponse
	(*SessionListGetRequest)(nil),  // 18: pb.SessionListGetRequest
	(*SessionListGetResponse)(nil), // 19: pb.SessionListGetResponse
	(*SessionRemoveRequest)(nil),   // 20: pb.SessionRemoveRequest
	(*SessionRemoveResponse)(nil),  // 21: pb.SessionRemoveResponse
	(*SessionSettingRequest)(nil),  // 22: pb.SessionSettingRequest
	(*SessionSettingResponse)(nil), // 23: pb.SessionSettingResponse
}
var file_ichat_message_proto_depIdxs = []int32{
	0,  // 0: pb.Message.MessageSync:input_type -> pb.MessageSyncRequest
	2,  // 1: pb.Message.MessageRecall:input_type -> pb.MessageRecallRequest
	4,  // 2: pb.Message.MessageAck:input_type -> pb.MessageAckRequest
	6,  // 3: pb.Message.MessageResp:input_type -> pb.MessageRespRequest
	8,  // 4: pb.Message.TalkToUser:input_type -> pb.TalkToUserRequest
	10, // 5: pb.Message.TalkToGroup:input_type -> pb.TalkToGroupRequest
	12, // 6: pb.Message.TalkToRoom:input_type -> pb.TalkToRoomRequest
	14, // 7: pb.Message.NoticeToUser:input_type -> pb.NoticeToUserRequest
	16, // 8: pb.Message.NoticeToGroup:input_type -> pb.NoticeToGroupRequest
	18, // 9: pb.Message.SessionListGet:input_type -> pb.SessionListGetRequest
	20, // 10: pb.Message.SessionRemove:input_type -> pb.SessionRemoveRequest
	22, // 11: pb.Message.SessionSetting:input_type -> pb.SessionSettingRequest
	1,  // 12: pb.Message.MessageSync:output_type -> pb.MessageSyncResponse
	3,  // 13: pb.Message.MessageRecall:output_type -> pb.MessageRecallResponse
	5,  // 14: pb.Message.MessageAck:output_type -> pb.MessageAckResponse
	7,  // 15: pb.Message.MessageResp:output_type -> pb.MessageRespResponse
	9,  // 16: pb.Message.TalkToUser:output_type -> pb.TalkToUserResponse
	11, // 17: pb.Message.TalkToGroup:output_type -> pb.TalkToGroupResponse
	13, // 18: pb.Message.TalkToRoom:output_type -> pb.TalkToRoomResponse
	15, // 19: pb.Message.NoticeToUser:output_type -> pb.NoticeToUserResponse
	17, // 20: pb.Message.NoticeToGroup:output_type -> pb.NoticeToGroupResponse
	19, // 21: pb.Message.SessionListGet:output_type -> pb.SessionListGetResponse
	21, // 22: pb.Message.SessionRemove:output_type -> pb.SessionRemoveResponse
	23, // 23: pb.Message.SessionSetting:output_type -> pb.SessionSettingResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ichat_message_proto_init() }
func file_ichat_message_proto_init() {
	if File_ichat_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ichat_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRecallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRecallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageAckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageAckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRespRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRespResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalkToUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalkToUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalkToGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalkToGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalkToRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalkToRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeToUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeToUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeToGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoticeToGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionListGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionListGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRemoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionSettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_message_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionSettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ichat_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ichat_message_proto_goTypes,
		DependencyIndexes: file_ichat_message_proto_depIdxs,
		MessageInfos:      file_ichat_message_proto_msgTypes,
	}.Build()
	File_ichat_message_proto = out.File
	file_ichat_message_proto_rawDesc = nil
	file_ichat_message_proto_goTypes = nil
	file_ichat_message_proto_depIdxs = nil
}
