// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.3
// source: ichat.relation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendsApplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To     string `protobuf:"bytes,1,opt,name=To,proto3" json:"To,omitempty"`
	Remark string `protobuf:"bytes,2,opt,name=Remark,proto3" json:"Remark,omitempty"`
}

func (x *FriendsApplyRequest) Reset() {
	*x = FriendsApplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsApplyRequest) ProtoMessage() {}

func (x *FriendsApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsApplyRequest.ProtoReflect.Descriptor instead.
func (*FriendsApplyRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{0}
}

func (x *FriendsApplyRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *FriendsApplyRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type FriendsApplyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FriendsApplyResponse) Reset() {
	*x = FriendsApplyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsApplyResponse) ProtoMessage() {}

func (x *FriendsApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsApplyResponse.ProtoReflect.Descriptor instead.
func (*FriendsApplyResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{1}
}

type FriendsApplyReplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FriendsApplyReplyRequest) Reset() {
	*x = FriendsApplyReplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsApplyReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsApplyReplyRequest) ProtoMessage() {}

func (x *FriendsApplyReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsApplyReplyRequest.ProtoReflect.Descriptor instead.
func (*FriendsApplyReplyRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{2}
}

type FriendsApplyReplyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FriendsApplyReplyResponse) Reset() {
	*x = FriendsApplyReplyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsApplyReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsApplyReplyResponse) ProtoMessage() {}

func (x *FriendsApplyReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsApplyReplyResponse.ProtoReflect.Descriptor instead.
func (*FriendsApplyReplyResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{3}
}

type FriendsEditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FriendsEditRequest) Reset() {
	*x = FriendsEditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsEditRequest) ProtoMessage() {}

func (x *FriendsEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsEditRequest.ProtoReflect.Descriptor instead.
func (*FriendsEditRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{4}
}

type FriendsEditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FriendsEditResponse) Reset() {
	*x = FriendsEditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsEditResponse) ProtoMessage() {}

func (x *FriendsEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsEditResponse.ProtoReflect.Descriptor instead.
func (*FriendsEditResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{5}
}

type FriendsDelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FriendsDelRequest) Reset() {
	*x = FriendsDelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsDelRequest) ProtoMessage() {}

func (x *FriendsDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsDelRequest.ProtoReflect.Descriptor instead.
func (*FriendsDelRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{6}
}

type FriendsDelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FriendsDelResponse) Reset() {
	*x = FriendsDelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendsDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsDelResponse) ProtoMessage() {}

func (x *FriendsDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsDelResponse.ProtoReflect.Descriptor instead.
func (*FriendsDelResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{7}
}

// 群
type GroupCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupCreateRequest) Reset() {
	*x = GroupCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateRequest) ProtoMessage() {}

func (x *GroupCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateRequest.ProtoReflect.Descriptor instead.
func (*GroupCreateRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{8}
}

type GroupCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupCreateResponse) Reset() {
	*x = GroupCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateResponse) ProtoMessage() {}

func (x *GroupCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateResponse.ProtoReflect.Descriptor instead.
func (*GroupCreateResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{9}
}

type GroupEditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupEditRequest) Reset() {
	*x = GroupEditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupEditRequest) ProtoMessage() {}

func (x *GroupEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupEditRequest.ProtoReflect.Descriptor instead.
func (*GroupEditRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{10}
}

type GroupEditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupEditResponse) Reset() {
	*x = GroupEditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupEditResponse) ProtoMessage() {}

func (x *GroupEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupEditResponse.ProtoReflect.Descriptor instead.
func (*GroupEditResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{11}
}

type GroupJoinApplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupJoinApplyRequest) Reset() {
	*x = GroupJoinApplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupJoinApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinApplyRequest) ProtoMessage() {}

func (x *GroupJoinApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinApplyRequest.ProtoReflect.Descriptor instead.
func (*GroupJoinApplyRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{12}
}

type GroupJoinApplyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupJoinApplyResponse) Reset() {
	*x = GroupJoinApplyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupJoinApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinApplyResponse) ProtoMessage() {}

func (x *GroupJoinApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinApplyResponse.ProtoReflect.Descriptor instead.
func (*GroupJoinApplyResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{13}
}

type GroupJoinApplyApproveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupJoinApplyApproveRequest) Reset() {
	*x = GroupJoinApplyApproveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupJoinApplyApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinApplyApproveRequest) ProtoMessage() {}

func (x *GroupJoinApplyApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinApplyApproveRequest.ProtoReflect.Descriptor instead.
func (*GroupJoinApplyApproveRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{14}
}

type GroupJoinApplyApproveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupJoinApplyApproveResponse) Reset() {
	*x = GroupJoinApplyApproveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupJoinApplyApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinApplyApproveResponse) ProtoMessage() {}

func (x *GroupJoinApplyApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinApplyApproveResponse.ProtoReflect.Descriptor instead.
func (*GroupJoinApplyApproveResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{15}
}

type GroupExitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupExitRequest) Reset() {
	*x = GroupExitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupExitRequest) ProtoMessage() {}

func (x *GroupExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupExitRequest.ProtoReflect.Descriptor instead.
func (*GroupExitRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{16}
}

type GroupExitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupExitResponse) Reset() {
	*x = GroupExitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupExitResponse) ProtoMessage() {}

func (x *GroupExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupExitResponse.ProtoReflect.Descriptor instead.
func (*GroupExitResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{17}
}

type GroupMemberRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupMemberRemoveRequest) Reset() {
	*x = GroupMemberRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMemberRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberRemoveRequest) ProtoMessage() {}

func (x *GroupMemberRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberRemoveRequest.ProtoReflect.Descriptor instead.
func (*GroupMemberRemoveRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{18}
}

type GroupMemberRemoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupMemberRemoveResponse) Reset() {
	*x = GroupMemberRemoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMemberRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberRemoveResponse) ProtoMessage() {}

func (x *GroupMemberRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberRemoveResponse.ProtoReflect.Descriptor instead.
func (*GroupMemberRemoveResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{19}
}

type GroupMemberSetUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupMemberSetUpRequest) Reset() {
	*x = GroupMemberSetUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMemberSetUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberSetUpRequest) ProtoMessage() {}

func (x *GroupMemberSetUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberSetUpRequest.ProtoReflect.Descriptor instead.
func (*GroupMemberSetUpRequest) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{20}
}

type GroupMemberSetUpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GroupMemberSetUpResponse) Reset() {
	*x = GroupMemberSetUpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ichat_relation_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupMemberSetUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberSetUpResponse) ProtoMessage() {}

func (x *GroupMemberSetUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ichat_relation_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberSetUpResponse.ProtoReflect.Descriptor instead.
func (*GroupMemberSetUpResponse) Descriptor() ([]byte, []int) {
	return file_ichat_relation_proto_rawDescGZIP(), []int{21}
}

var File_ichat_relation_proto protoreflect.FileDescriptor

var file_ichat_relation_proto_rawDesc = []byte{
	0x0a, 0x14, 0x69, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3d, 0x0a, 0x13, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x16, 0x0a, 0x14, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x73, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1a, 0x0a, 0x18, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a,
	0x19, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x15, 0x0a, 0x13, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x45, 0x64, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x73, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x12, 0x0a, 0x10, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x64, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x41, 0x70,
	0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x1d, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x13, 0x0a, 0x11, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19,
	0x0a, 0x17, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x74,
	0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x74, 0x55, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x98, 0x06, 0x0a, 0x08, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x0c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x11, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x73, 0x45, 0x64, 0x69, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x45, 0x64, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x73, 0x44, 0x65, 0x6c, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x73, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x64, 0x69,
	0x74, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x64, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x0e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x15, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4a, 0x6f, 0x69, 0x6e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x12, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4a, 0x6f, 0x69,
	0x6e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x78,
	0x69, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x78, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x50, 0x0a, 0x11, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4d, 0x0a, 0x10, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x53, 0x65, 0x74, 0x55, 0x70, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x74, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x53, 0x65, 0x74, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x1e, 0x5a, 0x1c, 0x69, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ichat_relation_proto_rawDescOnce sync.Once
	file_ichat_relation_proto_rawDescData = file_ichat_relation_proto_rawDesc
)

func file_ichat_relation_proto_rawDescGZIP() []byte {
	file_ichat_relation_proto_rawDescOnce.Do(func() {
		file_ichat_relation_proto_rawDescData = protoimpl.X.CompressGZIP(file_ichat_relation_proto_rawDescData)
	})
	return file_ichat_relation_proto_rawDescData
}

var file_ichat_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_ichat_relation_proto_goTypes = []interface{}{
	(*FriendsApplyRequest)(nil),           // 0: pb.FriendsApplyRequest
	(*FriendsApplyResponse)(nil),          // 1: pb.FriendsApplyResponse
	(*FriendsApplyReplyRequest)(nil),      // 2: pb.FriendsApplyReplyRequest
	(*FriendsApplyReplyResponse)(nil),     // 3: pb.FriendsApplyReplyResponse
	(*FriendsEditRequest)(nil),            // 4: pb.FriendsEditRequest
	(*FriendsEditResponse)(nil),           // 5: pb.FriendsEditResponse
	(*FriendsDelRequest)(nil),             // 6: pb.FriendsDelRequest
	(*FriendsDelResponse)(nil),            // 7: pb.FriendsDelResponse
	(*GroupCreateRequest)(nil),            // 8: pb.GroupCreateRequest
	(*GroupCreateResponse)(nil),           // 9: pb.GroupCreateResponse
	(*GroupEditRequest)(nil),              // 10: pb.GroupEditRequest
	(*GroupEditResponse)(nil),             // 11: pb.GroupEditResponse
	(*GroupJoinApplyRequest)(nil),         // 12: pb.GroupJoinApplyRequest
	(*GroupJoinApplyResponse)(nil),        // 13: pb.GroupJoinApplyResponse
	(*GroupJoinApplyApproveRequest)(nil),  // 14: pb.GroupJoinApplyApproveRequest
	(*GroupJoinApplyApproveResponse)(nil), // 15: pb.GroupJoinApplyApproveResponse
	(*GroupExitRequest)(nil),              // 16: pb.GroupExitRequest
	(*GroupExitResponse)(nil),             // 17: pb.GroupExitResponse
	(*GroupMemberRemoveRequest)(nil),      // 18: pb.GroupMemberRemoveRequest
	(*GroupMemberRemoveResponse)(nil),     // 19: pb.GroupMemberRemoveResponse
	(*GroupMemberSetUpRequest)(nil),       // 20: pb.GroupMemberSetUpRequest
	(*GroupMemberSetUpResponse)(nil),      // 21: pb.GroupMemberSetUpResponse
}
var file_ichat_relation_proto_depIdxs = []int32{
	0,  // 0: pb.Relation.FriendsApply:input_type -> pb.FriendsApplyRequest
	2,  // 1: pb.Relation.FriendsApplyReply:input_type -> pb.FriendsApplyReplyRequest
	4,  // 2: pb.Relation.FriendsEdit:input_type -> pb.FriendsEditRequest
	6,  // 3: pb.Relation.FriendsDel:input_type -> pb.FriendsDelRequest
	8,  // 4: pb.Relation.GroupCreate:input_type -> pb.GroupCreateRequest
	10, // 5: pb.Relation.GroupEdit:input_type -> pb.GroupEditRequest
	12, // 6: pb.Relation.GroupJoinApply:input_type -> pb.GroupJoinApplyRequest
	14, // 7: pb.Relation.GroupJoinApplyApprove:input_type -> pb.GroupJoinApplyApproveRequest
	16, // 8: pb.Relation.GroupExit:input_type -> pb.GroupExitRequest
	18, // 9: pb.Relation.GroupMemberRemove:input_type -> pb.GroupMemberRemoveRequest
	20, // 10: pb.Relation.GroupMemberSetUp:input_type -> pb.GroupMemberSetUpRequest
	1,  // 11: pb.Relation.FriendsApply:output_type -> pb.FriendsApplyResponse
	3,  // 12: pb.Relation.FriendsApplyReply:output_type -> pb.FriendsApplyReplyResponse
	5,  // 13: pb.Relation.FriendsEdit:output_type -> pb.FriendsEditResponse
	7,  // 14: pb.Relation.FriendsDel:output_type -> pb.FriendsDelResponse
	9,  // 15: pb.Relation.GroupCreate:output_type -> pb.GroupCreateResponse
	11, // 16: pb.Relation.GroupEdit:output_type -> pb.GroupEditResponse
	13, // 17: pb.Relation.GroupJoinApply:output_type -> pb.GroupJoinApplyResponse
	15, // 18: pb.Relation.GroupJoinApplyApprove:output_type -> pb.GroupJoinApplyApproveResponse
	17, // 19: pb.Relation.GroupExit:output_type -> pb.GroupExitResponse
	19, // 20: pb.Relation.GroupMemberRemove:output_type -> pb.GroupMemberRemoveResponse
	21, // 21: pb.Relation.GroupMemberSetUp:output_type -> pb.GroupMemberSetUpResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ichat_relation_proto_init() }
func file_ichat_relation_proto_init() {
	if File_ichat_relation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ichat_relation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsApplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsApplyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsApplyReplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsApplyReplyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsEditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsEditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsDelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendsDelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupEditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupEditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupJoinApplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupJoinApplyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupJoinApplyApproveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupJoinApplyApproveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupExitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupExitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMemberRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMemberRemoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMemberSetUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ichat_relation_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupMemberSetUpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ichat_relation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ichat_relation_proto_goTypes,
		DependencyIndexes: file_ichat_relation_proto_depIdxs,
		MessageInfos:      file_ichat_relation_proto_msgTypes,
	}.Build()
	File_ichat_relation_proto = out.File
	file_ichat_relation_proto_rawDesc = nil
	file_ichat_relation_proto_goTypes = nil
	file_ichat_relation_proto_depIdxs = nil
}
